### PR TITLE
Draft neo4j2solr code - needs work.

### PR DESCRIPTION
**Pull request by dosumis**
Query works in browser:

```cql
MATCH (n:DataSet:Individual) WHERE n.production = true 
WITH collect(DISTINCT {
     id: "vfb:class:" + n.iri, 
     iri: n.iri, 
     short_form: n.short_form, 
     shortform_autosuggest:[n.short_form], 
     obo_id: n.short_form, 
     label: n.label, 
     label_autosuggest: n.label, 
     label_autosuggest_ws: n.label, 
     label_autosuggest_e: n.label, 
     synonyms: n.synonyms, 
     synonym_autosuggest: coalesce(n.synonyms, []), 
     synonym_autosuggest_ws: coalesce(n.synonyms, []), 
     synonym_autosuggest_e: coalesce(n.synonyms, []), 
     autosuggest: [n.label] + n.synonyms, 
     autosuggest_e:[n.label] + n.synonyms, 
     description: [coalesce(n.description, n.label)], 
     ontology_name: 'vfb', 
     ontology_title: 'Virtual Fly Brain Knowledge Base', 
     ontology_prefix: 'VFB', 
     ontology_iri: 'http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl', 
     type: 'class', 
     is_defining_ontology: false, 
     has_children: false, 
     is_root: true}) AS doc
RETURN REDUCE(output = [], r IN doc | output + r) AS flat
```

but =>   

'code': 'Neo.DatabaseError.Statement.ExecutionFailure', 'message': 'Could not create token'\

When  run via  neo4j_connect.   This  error is usually a sign of referencing an unknown property key, 
 but don't think that can be true here.  @Robbie1977  - any ideas?

### CODE REVIEW

**Comment by Robbie1977** [comment]
> Query works in browser:
> 
> ```sql
> MATCH (n:DataSet:Individual) WHERE n.production = true 
> WITH collect(DISTINCT {
>      id: "vfb:class:" + n.iri, 
>      iri: n.iri, 
>      short_form: n.short_form, 
>      shortform_autosuggest:[n.short_form], 
>      obo_id: n.short_form, 
>      label: n.label, 
>      label_autosuggest: n.label, 
>      label_autosuggest_ws: n.label, 
>      label_autosuggest_e: n.label, 
>      synonyms: n.synonyms, 
>      synonym_autosuggest: coalesce(n.synonyms, []), 
>      synonym_autosuggest_ws: coalesce(n.synonyms, []), 
>      synonym_autosuggest_e: coalesce(n.synonyms, []), 
>      autosuggest: [n.label] + n.synonyms, 
>      autosuggest_e:[n.label] + n.synonyms, 
>      description: [coalesce(n.description, n.label)], 
>      ontology_name: 'vfb', 
>      ontology_title: 'Virtual Fly Brain Knowledge Base', 
>      ontology_prefix: 'VFB', 
>      ontology_iri: 'http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl', 
>      type: 'class', 
>      is_defining_ontology: false, 
>      has_children: false, 
>      is_root: true}) AS doc
> RETURN REDUCE(output = [], r IN doc | output + r) AS flat
> ```
> 
> but =>
> 
> 'code': 'Neo.DatabaseError.Statement.ExecutionFailure', 'message': 'Could not create token'\
> 
> When run via neo4j_connect. This error is usually a sign of referencing an unknown property key,
> but don't think that can be true here. @Robbie1977 - any ideas?

Maybe quote the key names inside
 ```WITH collect(DISTINCT {```

**Comment by dosumis** [comment]
> Maybe quote the key names inside
> WITH collect(DISTINCT {

That's not how neo4j maps work.  Quoting => 


 Invalid input ''': expected whitespace, comment, an identifier, UnsignedDecimalInteger, a property key name or '}' (line 3, column 6 (offset: 87))
"     'id': "vfb:class:" + n.iri }) "

**Comment by Robbie1977** [comment]
Current Error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/neo2solr/ols_neo2solr.py", line 34, in <module>
    print(r)
UnicodeEncodeError: 'ascii' codec can't encode character '\u03b6' in position 780338: ordinal not in range(128)
```

**Comment by Robbie1977** [comment]
This was only an issue with the print string conversion to ascii so swapped to utf-8 as a quick fix.

I'll work on pushing these results out to SOLR now

**Comment by Robbie1977** [comment]
working well found an issue with a pub node ('FBrf0229838') not having a short_form (not fixed in kbw and reloading pdb):
```
        },
        {
            "ontology_iri": "http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl",
            "synonym_autosuggest_ws": [],
            "description": [
                "Xu et al., 2017, Development 144(8): 1510--1517"
            ],
            "synonym_autosuggest_e": [],
            "ontology_name": "vfb",
            "synonym_autosuggest": [],
            "label": "Xu et al., 2017, Development 144(8): 1510--1517",
            "iri": "http://flybase.org/reports/FBrf0235264",
            "synonym": null,
            "label_autosuggest_e": "Xu et al., 2017, Development 144(8): 1510--1517",
            "shortform_autosuggest": [
                "FBrf0235264"
            ],
            "autosuggest_e": null,
            "ontology_title": "Virtual Fly Brain Knowledge Base",
            "id": "vfb:class:http://flybase.org/reports/FBrf0235264",
            "ontology_prefix": "VFB",
            "label_autosuggest_ws": "Xu et al., 2017, Development 144(8): 1510--1517",
            "label_autosuggest": "Xu et al., 2017, Development 144(8): 1510--1517",
            "autosuggest": null,
            "short_form": "FBrf0235264",
            "is_root": true,
            "type": "class",
            "has_children": false,
            "obo_id": "FBrf0235264",
            "is_defining_ontology": false
        }
    ]
}
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/neo2solr/ols_neo2solr.py", line 39, in <module>
    solr.add(json.loads(json.dumps(r))['flat'])
  File "/usr/local/lib/python3.6/dist-packages/pysolr.py", line 918, in add
    overwrite=overwrite, handler=handler)
  File "/usr/local/lib/python3.6/dist-packages/pysolr.py", line 500, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/usr/local/lib/python3.6/dist-packages/pysolr.py", line 412, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
pysolr.SolrError: Solr responded with an error (HTTP 400): [Reason: [doc=vfb:class:http://flybase.org/reports/FBrf0229838] missing required field: short_form]
```

**Comment by dosumis** [comment]
> working well found an issue with a pub node ('FBrf0229838') not having a short_form (now fixed in kbw and reloading pdb)

We should probably have a warning report (or schema check) to detect these.

**Comment by dosumis** [comment]
> This was only an issue with the print string conversion to ascii so swapped to utf-8 as a quick fix.

Doesn't Python 3 give us that by default?

**Comment by dosumis** [comment]
Code loooks good to me.  Happy to merge if you're ready.

**Comment by Robbie1977** [comment]
Current issue: 
image

**Comment by Robbie1977** [comment]
All working now

**Pull request merged**
