### PR TITLE
Draft xref expander.

### LINKED ISSUE #74: Write code to expand xrefs in ontology to linkouts on pdb

### PR DESCRIPTION
**Pull request by dosumis**
Fixes #74

Note - can't test against PDB until changes to Site names come through (for DoOR and Neuron_NDB) from fix in KBW.

@robbie1977 - this needs to be an additional job in PDB build.

### CODE REVIEW

**Comment by dosumis** [comment]
Found a problem with this:

Newly added links (local test pdb):

image

But other xrefs look like this:

image

The problem comes from the fact that hasDbXref has a label 'has databases crossreference', which I added for tidyness.  This is being used to generate the edge type.  The fix should not be in code, but in the KB.

**Comment by dosumis** [comment]
Hmmm - hit a further problem.  Property nodes in pdb are coming from imported ontologies, not (just) KB.  Labels are coming from there.  Maybe better to switch all xrefs to use the munged label.  Only alternative I can see is to manually specify this edge & all its details in code, but not sure this is sustainable - as seems likely this problem will recur from other sources.

**Comment by dosumis** [comment]
Not clear why we get hasDBXref as edge type when adding xrefs to KB using pattern_writer but munged labels when adding to pdb using code on this branch.

Here's the code from KB_pattern_writer.add_anatomy_image_set:

```py
                self.ew.add_annotation_axiom(s=anat_id['short_form'],
                                             r='hasDbXref',
                                             o=db,
                                             match_on='short_form',
                                             edge_annotations={'accession': acc},
                                             safe_label_edge=True
                                             )
```

Here's the new code:

```py
ew.add_annotation_axiom(s=c,
                                    r='hasDbXref',
                                    o=db,
                                    edge_annotations={
                                        "accession": acc,
                                    },
                                    match_on='short_form',
                                    safe_label_edge=True
                                    )
```

safe_label_edge=True + match_on='short_form' specifies that edge type should be a munged label taken from the Property node with the short_form specified in r.

In KB: 
iri: http://www.geneontology.org/formats/oboInOwl#hasDbXreflabel: database_cross_referenceshort_form: hasDbXref

PDB has a scary number of property nodes, and short_form is not sufficient to identify them:

ontology_name | IRI | label | short_form
-- | -- | -- | --
vfb | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref
fbdv | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref
fbcv | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref
ro | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref
so | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref
geno | http://www.geneontology.org/formats/oboInOwl#hasDbXref | has_dbxref | hasDbXref
fbbi | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref

**Comment by dosumis** [comment]
Local test: 
image

**Comment by Robbie1977** [comment]
First test failed:
```
-e travis_fold:start:expand_xrefs
** expand_xrefs **
17:43.17 - python3 /opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/neo2neo/expand_xrefs.py http://192.168.0.2:7474 neo4j vfb
ERROR: An error was encountered with the job.
Tailing the last 500 lines of output:
python3 /opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/neo2neo/expand_xrefs.py http://192.168.0.2:7474 neo4j vfb
Traceback (most recent call last):
  File "/opt/VFB/VFB_neo4j/src/uk/ac/ebi/vfb/neo4j/neo2neo/expand_xrefs.py", line 1, in <module>
    from ..neo4j_tools import neo4j_connect, results_2_dict_list
ValueError: attempted relative import beyond top-level package
ValueError: attempted relative import beyond top-level package
-e travis_fold:end:expand_xrefs
```

**Comment by Robbie1977** [comment]
Live on https://v2a.virtualflybrain.org/?i=VFB_00017894,FBbt_00003840

Though need to modify the NDB links to use https://flybrain-ndb.virtualflybrain.org/neuronrec-10036.html site and layout

**Pull request merged**
